# Formatted for the JetBrains REST client
# See https://www.jetbrains.com/help/rider/Http_client_in__product__code_editor.html

@HostAddress = https://localhost:7233
@ApiKey = client-api-key-1
@ApiKey2 = client-api-key-2

### Check health.
GET {{HostAddress}}/health
Accept: application/json

### List all currently active notifications.
GET {{HostAddress}}/current
Accept: application/json

### List all future scheduled notifications.
GET {{HostAddress}}/future
Accept: application/json

### List all notifications.
GET {{HostAddress}}/all
Accept: application/json
X-API-Key: {{ApiKey}}

### List all notifications using alternate API key.
GET {{HostAddress}}/all
Accept: application/json
X-API-Key: {{ApiKey2}}

### Create a new notification.
POST {{HostAddress}}/add
Content-Type: application/json
X-API-Key: {{ApiKey}}

{
  "Message": "New notification",
  "DisplayStart": "2025-06-25T08:00",
  "DisplayEnd": "2050-08-01T21:00"
}

> {%
    client.global.set("newId", response.body.id);
%}

### Deactivate the new notification.
POST {{HostAddress}}/deactivate
Content-Type: application/json
X-API-Key: {{ApiKey}}

{
  "Id": "{{newId}}"
}

### Deactivate a current notification.
POST {{HostAddress}}/deactivate
Content-Type: application/json
X-API-Key: {{ApiKey}}

{
  "Id": "00000000-0000-0000-0000-000000000001"
}
